language: python
python:
- '2.7'
- '3.3'

before_script:
    - sudo apt install texlive-luatex  texlive-pictures
    - sudo apt install python-numpy python-matplotlib 

script :
    - make build
    - make test
