sudo: required
language: python
python:
- '2.7'
- '3.3'

cache:
    apt: true

before_install:
    - sudo add-apt-repository ppa:jonathonf/texlive-2016 -y
    - sudo apt-get update -q

before_script:
    - sudo apt install texlive-base texlive-latex-base xzdec  -y
    - # sudo ./_travis/install-tl-ubuntu -g # This takes 36 mins on travis. Not worth it.
    - sudo tlmgr init-usertree
    - sudo tlmgr install pgfplots standalone pgf  xkeyval siunitx chemfig
    - sudo apt install python-numpy python3-numpy -y
    - sudo apt install imagemagick -y

script :
    - make build
    - make test
    - make png
