language: python
python:
- '2.7'
- '3.3'

before_script:
    - sudo apt install texlive-luatex  texlive-pictures texlive-latex-extra
    - sudo apt install python-numpy python3-numpy 
    - sudo apt install imagemagick

script :
    - make build
    - make test
