sudo: required
language: python
python:
- '2.7'
- '3.3'

before_install:
    - sudo add-apt-repository ppa:jonathonf/texlive-2016 -y
    - sudo apt-get update -q
    - sudo apt-get upgrade

before_script:
    - sudo apt install texlive-full -y
    - sudo apt install python-numpy python3-numpy -y
    - sudo apt install imagemagick -y

script :
    - make build
    - make test
    - make png
